name: react-native-android-build-apk
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn --network-concurrency 1 --network-timeout 120000
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleDebug
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
